//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBFormDBFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LOBFormEntities : DbContext
    {
        public LOBFormEntities()
            : base("name=LOBFormEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOBLeaveAppForms> LOBLeaveAppForms { get; set; }
        public virtual DbSet<LOBLeaveCategories> LOBLeaveCategories { get; set; }
        public virtual DbSet<LOBMyUsers> LOBMyUsers { get; set; }
        public virtual DbSet<LOBOnCallPhones> LOBOnCallPhones { get; set; }
        public virtual DbSet<LOBProjects> LOBProjects { get; set; }
        public virtual DbSet<LOBWorkingLogs> LOBWorkingLogs { get; set; }
    }
}
