//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBFormDBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOBLeaveAppForms
    {
        public int LeaveAppFormId { get; set; }
        public System.DateTime FormDate { get; set; }
        public string Category { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime CompleteDate { get; set; }
        public string AgentName { get; set; }
        public string LeaveCause { get; set; }
        public string FormsStatus { get; set; }
        public string ApproveResult { get; set; }
        public Nullable<int> Owner_MyUserId { get; set; }
        public double Hours { get; set; }
        public int AgentId { get; set; }
    
        public virtual LOBMyUsers LOBMyUsers { get; set; }
    }
}
