//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOBFormDBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOBMyUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOBMyUsers()
        {
            this.LOBLeaveAppForms = new HashSet<LOBLeaveAppForms>();
            this.LOBWorkingLogs = new HashSet<LOBWorkingLogs>();
        }
    
        public int MyUserId { get; set; }
        public string DepartmentName { get; set; }
        public string Name { get; set; }
        public string EmployeeID { get; set; }
        public string Password { get; set; }
        public bool IsManager { get; set; }
        public Nullable<System.DateTimeOffset> CreatedAt { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedAt { get; set; }
        public int ManagerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOBLeaveAppForms> LOBLeaveAppForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOBWorkingLogs> LOBWorkingLogs { get; set; }
    }
}
